/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UAS_PBO;

import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author KYC
 */
public class PilihMatkul extends javax.swing.JFrame {

    DefaultTableModel model;
    String kelas;
    String kode;
    String nama;
    String wp;
    String semester;
    String sks;
    
    public PilihMatkul() {
        initComponents();
        String []judul = {"ID","Kelas","Kode","Nama","W/P","Semester","SKS"};
        model = new DefaultTableModel(judul,0);
        tblKRS.setModel(model);
        tampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKRS = new javax.swing.JTable();
        cmbKategori = new javax.swing.JComboBox<>();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblKRS.setBackground(new java.awt.Color(204, 204, 204));
        tblKRS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKRS.setSelectionBackground(java.awt.SystemColor.activeCaption);
        tblKRS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKRSMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKRS);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 630, 310));

        cmbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kode", "Nama Mata Kuliah" }));
        jPanel1.add(cmbKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 160, 30));
        jPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 340, 30));

        btnSearch.setBackground(new java.awt.Color(204, 204, 204));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/images-removebg-preview.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 110, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DAFTAR MATA KULIAH");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        btnTambah.setBackground(new java.awt.Color(204, 204, 204));
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/confirm.png"))); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        jPanel1.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, -1, -1));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cancel.png"))); // NOI18N
        jButton1.setText("Batal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/background 2.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
         if (kelas != null && !kelas.isEmpty()) {
            try {
                int sksInt = Integer.parseInt(sks);
                int semesterInt = Integer.parseInt(semester);
                String id_user = User.getInstance().getUsername();

                try (Connection conn = koneksi.getConnection();
                     PreparedStatement stmt = conn.prepareStatement("SELECT SUM(sks) FROM tbl_krs WHERE id_akun = ?");
                     PreparedStatement stmt2 = conn.prepareStatement("SELECT * FROM tbl_krs WHERE nama = ? AND id_akun = ?");
                     PreparedStatement stmt3 = conn.prepareStatement("INSERT INTO tbl_krs (id_akun, kelas, kode, nama, wp, semester, sks) VALUES (?, ?, ?, ?, ?, ?, ?)")) {

                    stmt.setString(1, id_user);

                    ResultSet rs = stmt.executeQuery();
                    if (rs.next()) {
                        int totalSks = rs.getInt(1);
                        if (totalSks + sksInt <= 24) {
                            stmt2.setString(1, nama);
                            stmt2.setString(2, id_user);

                            ResultSet rs2 = stmt2.executeQuery();

                            if (rs2.next()) {
                                JOptionPane.showMessageDialog(this, "Nama Mata Kuliah Sudah Ada");
                            } else {
                                stmt3.setString(1, id_user);
                                stmt3.setString(2, kelas);
                                stmt3.setString(3, kode);
                                stmt3.setString(4, nama);
                                stmt3.setString(5, wp);
                                stmt3.setInt(6, semesterInt);
                                stmt3.setInt(7, sksInt);

                                int rowsAffected = stmt3.executeUpdate();

                                if (rowsAffected > 0) {
                                    JOptionPane.showMessageDialog(this, "Penambahan Berhasil!");
                                    menuUser user = new menuUser();
                                    user.tampilData();
                                    user.hitungSKS(); // Update SKS count
                                    user.setVisible(true);
                                    this.dispose();
                                } else {
                                    JOptionPane.showMessageDialog(this, "Gagal Menambahkan Data");
                                }
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "SKS Melebihi Batas Maksimal (24)");
                        }
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(PilihMatkul.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Semester dan SKS harus berupa angka.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Belum Ada Mata Kuliah Yang Dipilih");
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        menuUser user = new menuUser();
        user.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblKRSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKRSMouseClicked
        int row = tblKRS.rowAtPoint(evt.getPoint());
        Object kelasValue  = tblKRS.getValueAt(row, 1);
        Object kodeValue  = tblKRS.getValueAt(row, 2);
        Object namaValue  = tblKRS.getValueAt(row, 3);
        Object wpValue  = tblKRS.getValueAt(row, 4);
        Object semesterValue  = tblKRS.getValueAt(row, 5);
        Object sksValue  = tblKRS.getValueAt(row, 6);
        kelas = kelasValue.toString();
        kode = kodeValue.toString();
        nama = namaValue.toString();
        wp = wpValue.toString();
        semester = semesterValue.toString();
        sks = sksValue.toString();
    }//GEN-LAST:event_tblKRSMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        tampilData();
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihMatkul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihMatkul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihMatkul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihMatkul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PilihMatkul().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cmbKategori;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKRS;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
    public void tampilData() {
        int row = tblKRS.getRowCount();
        for (int i = 0; i < row; i++) {
            model.removeRow(0);
        }
        String kategori;
        String Search;
        int selectedIndex = cmbKategori.getSelectedIndex();
        if (selectedIndex == 0){
            kategori = "kode";
        }else{
            kategori = "nama";
        }
        Search = txtSearch.getText();
        
        try {
            String sql = "SELECT * FROM tbl_matkul WHERE " + kategori + " LIKE ?";
            Connection conn = koneksi.getConnection();
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, "%" + Search + "%");
            ResultSet rs = stmt.executeQuery();
            while (rs.next()) {
                String data[] = { rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7) };
                model.addRow(data);
            }
        } catch (Exception e) {
            System.out.println("Ambil Data Gagal");
        }
    }
}
